---
-
  name: "Rbenv Ruby Runtime Environment Playbook"
  hosts: all
  remote_user: ubuntu
  become: true
  roles:
    - rbenv:
        env: user
        ruby_version: "2.3.3"
        version: v1.0.0
      rbenv_plugins:
        - { name: "ruby-build",
            repo: "git://github.com/sstephenson/ruby-build.git",
            version: "v20161121" }
        - { name: "rbenv-vars",
            repo: "https://github.com/sstephenson/rbenv-vars.git",
            version: "v1.2.0" }
        - { name: "rbenv-bundler",
            repo: "https://github.com/carsomyr/rbenv-bundler.git",
            version: "0.99" }
        - { name: "rbenv-installer",
            repo: "https://github.com/rbenv/rbenv-installer.git",
            version: "bc21e7055dcc8f5f9bc66ce0c78cc9ae0c28cd7a" }
        - { name: "rbenv-default-gems",
            repo: "https://github.com/rbenv/rbenv-default-gems.git",
            version: "v1.0.0" }
        - { name: "rbenv-update",
            repo: "https://github.com/rkh/rbenv-update.git",
            version: "1961fa180280bb50b64cbbffe6a5df7cf70f5e50" }
        - { name: "rbenv-whatis",
            repo: "https://github.com/rkh/rbenv-whatis.git",
            version: "v1.0.0" }
        - { name: "rbenv-use",
            repo: "https://github.com/rkh/rbenv-use.git",
            version: "v1.0.0" }
      rbenv_users:
        - deploy
      rbenv_owner: 'deploy'
      rbenv_group: 'deploy'
      role: rbenv

